/**
 * Reference-generation contract (Phase 2 flagship — "管理免费、生成收费").
 *
 * The first cost-incurring slice: an entity's references are GENERATED by a
 * model provider instead of uploaded. The web enqueues a RefGenJob, the
 * worker calls the provider (mock in dev/tests, fal in prod), stores the
 * outputs content-addressed, and attaches them as ReferenceImages — exactly
 * the render pipeline's shape, a different verb.
 *
 * Model-neutrality (the "Target chip" backend) lives in the Generation
 * provider port: GENERATION_PROVIDER=mock|fal selects the implementation,
 * zero code change. v1 ships one model (Seedream, the $0.035 workhorse from
 * the provider research); the port is where Kling-elements / Modal-ComfyUI /
 * other models plug in later.
 *
 * D19-style trust boundary: the request carries NO image URLs. Conditioning
 * (e.g. the logo to print on a garment) is the entity's OWN existing
 * reference images, resolved server-side from entityId — a client can't
 * condition a generation on arbitrary bytes.
 */
import { z } from "zod";

/** v1 model menu — one workhorse. The port, not this list, is the extension
 *  point; adding a model is a provider concern, not a contract change. */
export const REFGEN_MODELS = ["seedream"] as const;
export type RefGenModel = (typeof REFGEN_MODELS)[number];

/** Seedream emits 1–6 images per call; cap conditioning at its 10-ref limit. */
export const MAX_REFGEN_COUNT = 6;
export const MAX_CONDITIONING_IMAGES = 10;
export const MAX_REFGEN_PROMPT = 2000;

/** Reference generation modes — REFSHEET legacy multi-view, BASE single t2i
 *  identity anchor, VARIANT single i2i look from the base. */
export const REFGEN_MODES = ["REFSHEET", "BASE", "VARIANT"] as const;
export type RefGenMode = (typeof REFGEN_MODES)[number];
/**
 * RECORD-ONLY 参考图成本记账基准(RefGenJob.spentUsd + 毛利报表)—— **不是收费**。
 * 参考图一律按 `pricedRefgenCredits` 收 1 credit/张,与这个数无关。
 *
 * $0.035/张,与正片图片同一张账单基数(按张计价,不分尺寸比例)。
 * 来源 https://docs.byteplus.com/en/docs/ModelArk/Pricing(2026-08-05 核)。
 * 旧值 $0.04 是 fal 基数占位,高记约 14%;#644 改真。刻意与 `GEN_PRICE_USD_PER_IMAGE`
 * 保持**各自独立**的常量:两条链路将来可能换不同模型。
 */
export const REFGEN_PRICE_USD_PER_IMAGE = 0.035;

/** What the web action accepts. Conditioning is derived server-side from the
 *  entity, so it is deliberately absent here (D19 trust boundary). */
export const refGenRequest = z
  .object({
    entityId: z.string().min(1).max(64),
    prompt: z.string().trim().min(1).max(MAX_REFGEN_PROMPT),
    count: z.number().int().min(1).max(MAX_REFGEN_COUNT),
    model: z.enum(REFGEN_MODELS).default("seedream"),
    mode: z.enum(REFGEN_MODES).default("REFSHEET"),
    variantId: z.string().min(1).max(64).optional(),
  })
  .strict()
  .superRefine((v, ctx) => {
    // VARIANT ⟺ variantId — a VARIANT job must name its target, and a variantId
    // is meaningless (and a sign of a confused caller) outside VARIANT mode.
    if (v.mode === "VARIANT" && !v.variantId)
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: "VARIANT mode requires a variantId", path: ["variantId"] });
    if (v.mode !== "VARIANT" && v.variantId)
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: "variantId only valid in VARIANT mode", path: ["variantId"] });
  });
export type RefGenRequest = z.infer<typeof refGenRequest>;

/** pg-boss payload — the row holds the real data, the job just names it
 *  (mirrors renderJobData). */
export const refGenJobData = z.object({ refGenJobId: z.string().min(1).max(64) }).strict();
export type RefGenJobData = z.infer<typeof refGenJobData>;

export const REFGEN_QUEUE = "refgen";
export const REFGEN_DLQ = `${REFGEN_QUEUE}.dlq`;
export const REFGEN_RETRY_LIMIT = 2;
/** Shared so either side creates the queue idempotently (same as render). */
export const REFGEN_QUEUE_POLICY = {
  retryLimit: REFGEN_RETRY_LIMIT,
  retryBackoff: true,
  // base seconds for the retry backoff (see GEN_QUEUE_POLICY): without it pg-boss defaults
  // retry_delay=0 and `retryBackoff` is a silent no-op → a failed paid refgen retries instantly.
  retryDelay: 30,
  // > the longest realistic fal call so a still-running job is never expired +
  // redelivered (which would let the duplicate-delivery fail-closed wrongly FAIL an
  // active paid job). Both web (dispatch) and worker (consumer) create the queue
  // with THIS policy, so boot order can't leave them split.
  expireInSeconds: 60 * 20,
  deadLetter: REFGEN_DLQ,
} as const;

/* ---------------- provider port (the model-neutral backend) ---------------- */

/** What the worker hands a provider. inputImageUrls are short-lived presigned
 *  GETs the provider can fetch (the entity's conditioning refs); empty for a
 *  pure text-to-image generation. */
export interface GenerationRequest {
  prompt: string;
  inputImageUrls: string[];
  count: number;
  model: RefGenModel;
  /** 商家要的画幅(`GEN_IMAGE_ASPECTS` 之一)。缺省 ⇒ 适配器按默认画幅(方图)出图。
   *  参考图(refgen)不设画幅,始终走默认 —— 参考图是给引擎看的素材,不是交付物。 */
  aspectRatio?: string;
  /** #777:这 `count` 张是**一组要连贯的图**(同模特多角度/同产品多尺寸)。
   *  true ⇒ 适配器**一次请求**出齐整组;缺省 ⇒ 一张一次请求,与今日逐字一致。
   *  做不到这件事的适配器必须在**付费之前**拒绝,不得静默降级成 N 张散图 ——
   *  商家批的是「一组」,收了钱交一堆互不相干的图就是一次没说出口的降级。 */
  coherentSet?: boolean;
}

/** One generated image, already downloaded by the provider — the worker
 *  stores these bytes content-addressed (same as any asset). */
export interface GeneratedImage {
  bytes: Uint8Array;
  ext: string;
}

/** What the worker hands a provider to animate an image into a clip (i2v).
 *  imageUrl is a short-lived presigned GET the provider fetches. */
export interface VideoRequest {
  prompt: string;
  imageUrl: string;
  /** optional end frame — i2v interpolates source→tail (Kling tail_image_url). */
  tailImageUrl?: string;
  /** optional whole-clip reference video — a short-lived presigned GET the provider
   *  passes to Seedance as role:"reference_video". BytePlus 2.0 only; Fal rejects it. */
  refVideoUrl?: string;
  durationSeconds: number;
  model: string;
  // per-model controls (resolved from the job; the provider maps each to the
  // model's fal param). Absent → the model's default.
  resolution?: string;
  aspectRatio?: string;
  fps?: number;
  audio?: boolean;
  /** #782 — ask the engine to hand back this clip's LAST FRAME as a still.
   *  Free: the Ark video endpoint bills the clip, not the extra picture, so this
   *  flag never adds a charge and never changes what the merchant is quoted.
   *  A provider that has no such mechanism simply ignores it and returns no
   *  `lastFrame` — never an error, because nothing was promised or billed. */
  returnLastFrame?: boolean;
}

/** One generated clip, already downloaded by the provider. */
export interface GeneratedVideo {
  bytes: Uint8Array;
  ext: string;
  /** #782 — the clip's last frame, present ONLY when `returnLastFrame` was asked
   *  for AND the engine returned a usable still. Absent is the normal, safe
   *  outcome: the clip itself is unaffected, so a missing tail must never fail
   *  (or re-charge) a generation that already succeeded. */
  lastFrame?: { bytes: Uint8Array; ext: string };
}

export interface GenerationProvider {
  /** Stable id for logs/audit (e.g. "mock", "fal:seedream"). */
  readonly name: string;
  /** Generate `req.count` images. Throws on provider failure so the worker's
   *  pg-boss retry/DLQ handles it (no partial-success contract — all or the
   *  job retries). */
  generate(req: GenerationRequest): Promise<GeneratedImage[]>;
  /** Image-to-video: animate one image into a clip. Throws on failure. */
  generateVideo(req: VideoRequest): Promise<GeneratedVideo>;
}
