/**
 * Reference-generation contract (Phase 2 flagship — "管理免费、生成收费").
 *
 * The first cost-incurring slice: an entity's references are GENERATED by a
 * model provider instead of uploaded. The web enqueues a RefGenJob, the
 * worker calls the provider (mock in dev/tests, fal in prod), stores the
 * outputs content-addressed, and attaches them as ReferenceImages — exactly
 * the render pipeline's shape, a different verb.
 *
 * Model-neutrality (the "Target chip" backend) lives in the Generation
 * provider port: GENERATION_PROVIDER=mock|fal selects the implementation,
 * zero code change. v1 ships one model (Seedream, the $0.035 workhorse from
 * the provider research); the port is where Kling-elements / Modal-ComfyUI /
 * other models plug in later.
 *
 * D19-style trust boundary: the request carries NO image URLs. Conditioning
 * (e.g. the logo to print on a garment) is the entity's OWN existing
 * reference images, resolved server-side from entityId — a client can't
 * condition a generation on arbitrary bytes.
 */
import { z } from "zod";

/** v1 model menu — one workhorse. The port, not this list, is the extension
 *  point; adding a model is a provider concern, not a contract change. */
export const REFGEN_MODELS = ["seedream"] as const;
export type RefGenModel = (typeof REFGEN_MODELS)[number];

/** Seedream emits 1–6 images per call; cap conditioning at its 10-ref limit. */
export const MAX_REFGEN_COUNT = 6;
export const MAX_CONDITIONING_IMAGES = 10;
export const MAX_REFGEN_PROMPT = 2000;
/** Per-image price hint shown at the point of spend (fal Seedream 4.5).
 *  Display only — billing is a later slice. */
export const REFGEN_PRICE_USD_PER_IMAGE = 0.04;

/** What the web action accepts. Conditioning is derived server-side from the
 *  entity, so it is deliberately absent here (D19 trust boundary). */
export const refGenRequest = z
  .object({
    entityId: z.string().min(1).max(64),
    prompt: z.string().trim().min(1).max(MAX_REFGEN_PROMPT),
    count: z.number().int().min(1).max(MAX_REFGEN_COUNT),
    model: z.enum(REFGEN_MODELS).default("seedream"),
  })
  .strict();
export type RefGenRequest = z.infer<typeof refGenRequest>;

/** pg-boss payload — the row holds the real data, the job just names it
 *  (mirrors renderJobData). */
export const refGenJobData = z.object({ refGenJobId: z.string().min(1).max(64) }).strict();
export type RefGenJobData = z.infer<typeof refGenJobData>;

export const REFGEN_QUEUE = "refgen";
export const REFGEN_DLQ = `${REFGEN_QUEUE}.dlq`;
export const REFGEN_RETRY_LIMIT = 2;
/** Shared so either side creates the queue idempotently (same as render). */
export const REFGEN_QUEUE_POLICY = {
  retryLimit: REFGEN_RETRY_LIMIT,
  retryBackoff: true,
  deadLetter: REFGEN_DLQ,
} as const;

/* ---------------- provider port (the model-neutral backend) ---------------- */

/** What the worker hands a provider. inputImageUrls are short-lived presigned
 *  GETs the provider can fetch (the entity's conditioning refs); empty for a
 *  pure text-to-image generation. */
export interface GenerationRequest {
  prompt: string;
  inputImageUrls: string[];
  count: number;
  model: RefGenModel;
}

/** One generated image, already downloaded by the provider — the worker
 *  stores these bytes content-addressed (same as any asset). */
export interface GeneratedImage {
  bytes: Uint8Array;
  ext: string;
}

/** What the worker hands a provider to animate an image into a clip (i2v).
 *  imageUrl is a short-lived presigned GET the provider fetches. */
export interface VideoRequest {
  prompt: string;
  imageUrl: string;
  /** optional end frame — i2v interpolates source→tail (Kling tail_image_url). */
  tailImageUrl?: string;
  durationSeconds: number;
  model: string;
  // per-model controls (resolved from the job; the provider maps each to the
  // model's fal param). Absent → the model's default.
  resolution?: string;
  aspectRatio?: string;
  fps?: number;
  audio?: boolean;
}

/** One generated clip, already downloaded by the provider. */
export interface GeneratedVideo {
  bytes: Uint8Array;
  ext: string;
}

export interface GenerationProvider {
  /** Stable id for logs/audit (e.g. "mock", "fal:seedream"). */
  readonly name: string;
  /** Generate `req.count` images. Throws on provider failure so the worker's
   *  pg-boss retry/DLQ handles it (no partial-success contract — all or the
   *  job retries). */
  generate(req: GenerationRequest): Promise<GeneratedImage[]>;
  /** Image-to-video: animate one image into a clip. Throws on failure. */
  generateVideo(req: VideoRequest): Promise<GeneratedVideo>;
}
