import type { BrandSectionKey, ContextRecord } from "./model"

const voicePreview = {
  withoutPreview: "Discover our latest gift box, designed for every celebration.",
  withPreview: "A thoughtful gift, made easy. Pick a box they’ll love and we’ll handle the rest.",
}

export const BRAND_CONTEXT_FIXTURES: Record<BrandSectionKey, readonly ContextRecord[]> = {
  "brand-voice": [
    {
      id: "warm-practical-founder",
      name: "Warm, practical founder",
      description: "Clear, encouraging and useful. Sounds like a founder helping another founder move forward.",
      status: "Ready",
      updated: "Updated today",
      source: "Company website",
      sourceDetail: "fikirtive.com/about",
      instructions: ["Lead with the useful answer", "Use plain, confident language", "Avoid hype and jargon"],
      usage: ["Merdeka launch · Product photo copy", "Weekend tea launch · Video concept"],
      history: ["Added website evidence · Today", "Voice instructions reviewed · Today"],
      ...voicePreview,
    },
    {
      id: "bold-challenger",
      name: "Bold challenger",
      description: "Direct and energetic for launches that need a stronger point of view.",
      status: "Draft",
      updated: "Edited yesterday",
      source: "Pasted text",
      sourceDetail: "Founder notes",
      instructions: ["Make the contrast obvious", "Prefer short active sentences", "Never sound aggressive"],
      usage: ["Not used yet"],
      history: ["Draft created · Yesterday"],
      withoutPreview: voicePreview.withoutPreview,
      withPreview: "Skip the ordinary gift. Make their Merdeka moment impossible to forget.",
    },
    {
      id: "calm-expert",
      name: "Calm expert",
      description: "Measured, credible guidance for educational or high-consideration content.",
      status: "Draft",
      updated: "Edited 3 days ago",
      source: "File upload",
      sourceDetail: "Brand workshop notes.pdf",
      instructions: ["Explain before persuading", "Use specific evidence", "Avoid urgency language"],
      usage: ["Not used yet"],
      history: ["File reviewed · 3 days ago"],
      withoutPreview: voicePreview.withoutPreview,
      withPreview: "Choose a gift box by occasion, budget and delivery date—with every detail explained upfront.",
    },
    {
      id: "friendly-companion",
      name: "Friendly companion",
      description: "Conversational and light for everyday social content.",
      status: "Processing",
      updated: "Reading source now",
      source: "Company website",
      sourceDetail: "fikirtive.com/journal",
      instructions: ["Processing source…"],
      usage: ["Not available until processing finishes"],
      history: ["URL added · 2 minutes ago"],
      withoutPreview: voicePreview.withoutPreview,
      withPreview: "Preview becomes available when the source is ready.",
    },
  ],
  audiences: [
    {
      id: "busy-small-business-founders",
      name: "Busy small-business founders",
      description: "Founder-operators who need polished marketing without adding another complicated tool.",
      status: "Ready",
      updated: "Updated today",
      source: "Customer interviews",
      sourceDetail: "Founder interview notes",
      instructions: ["Show time saved", "Explain the next step clearly", "Respect limited budget and attention"],
      usage: ["Merdeka launch · Primary audience"],
      history: ["Interview evidence added · Today"],
      withoutPreview: "Create your next campaign with our AI tools.",
      withPreview: "Turn one idea into campaign-ready creative—without another week lost to tools and revisions.",
    },
    {
      id: "independent-retailers",
      name: "Independent retailers",
      description: "Local retailers balancing seasonal launches, stock and a small team.",
      status: "Draft",
      updated: "Edited yesterday",
      source: "Pasted text",
      sourceDetail: "Sales notes",
      instructions: ["Focus on seasonal speed", "Use retail examples"],
      usage: ["Not used yet"],
      history: ["Draft created · Yesterday"],
      withoutPreview: "Launch seasonal content quickly.",
      withPreview: "Get your seasonal campaign ready before the stock hits the shelf.",
    },
  ],
  "knowledge-base": [
    {
      id: "approved-product-claims",
      name: "Approved product claims",
      description: "Claims Otto may use when describing Fikirtive creation capabilities.",
      status: "Ready",
      updated: "Updated yesterday",
      source: "Company website",
      sourceDetail: "fikirtive.com/product",
      instructions: ["Use only listed capabilities", "Do not promise guaranteed performance", "Keep Seedance model names current"],
      usage: ["Weekend tea launch · Product description"],
      history: ["Website checked · Yesterday"],
      withoutPreview: "Generate any marketing asset instantly.",
      withPreview: "Create and refine campaign-ready images and short videos with Otto.",
    },
  ],
  "style-guide": [
    {
      id: "writing-conventions",
      name: "Writing conventions",
      description: "The small rules that keep Fikirtive copy consistent across product and marketing.",
      status: "Ready",
      updated: "Updated 4 days ago",
      source: "Pasted text",
      sourceDetail: "Brand guideline v4",
      instructions: ["Use sentence case", "Write Otto with a capital O", "Prefer create over generate in founder-facing copy"],
      usage: ["Merdeka launch · All outputs", "Weekend tea launch · All outputs"],
      history: ["Sentence case rule clarified · 4 days ago"],
      withoutPreview: "GENERATE YOUR NEXT CAMPAIGN WITH OTTO",
      withPreview: "Create your next campaign with Otto",
    },
  ],
  "visual-guidelines": [
    {
      id: "warm-editorial-product-scenes",
      name: "Warm editorial product scenes",
      description: "Natural light, tactile materials and a confident focal product with room for copy.",
      status: "Ready",
      updated: "Updated today",
      source: "Library collection",
      sourceDetail: "Approved product references",
      instructions: ["Use warm natural light", "Keep one clear product focus", "Avoid glossy synthetic surfaces"],
      usage: ["Merdeka launch · Gift-box hero"],
      history: ["Three Library references linked · Today"],
      withoutPreview: "A generic gift box on a white background.",
      withPreview: "A warm editorial gift-box scene with tactile paper, soft daylight and clean negative space.",
    },
  ],
}
