import type { SkillMeta } from "./registry.js";

/** Deterministic markdown table of all skills. Pure — same input, same bytes. */
export function renderCatalog(meta: SkillMeta[]): string {
  const rows = [...meta]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map(
      (m) =>
        `| ${m.name} | ${m.cost} | ${m.effect} | ${m.reach} | ${m.needsApproval ? "✅" : "❌"} | ${m.description.replace(/\n/g, " ").slice(0, 80)} |`,
    );
  return [
    "<!-- GENERATED by `pnpm --filter @fikirtive/otto run catalog`. Do not edit by hand. -->",
    "# Otto Skill Catalog",
    "",
    "| skill | cost | effect | reach | needsApproval | description |",
    "|---|---|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}
