/**
 * 技能文件柜的**纯机制**（`docs/specs/otto-engine.md` §7.2⑥ · S1 §1 九问 4 的取用三规则）。
 *
 * 这里只有解析、排序、渲染与匹配 —— 没有 fs，没有 I/O。三个调用方各取所需：
 *   · `scripts/gen-knowledge.ts`（build 期）：读盘 → `parseCabinetFile` → `renderCabinetModule`；
 *   · `instructions.ts`（运行期装配器）：`matchKnowledge` 决定这一轮装哪几份全文；
 *   · `knowledge-cabinet.test.ts`：三条规则各一组行为测试（ENGINE-A7）。
 *
 * 取用三规则（S1 已冻结，逐条对应下面的函数）：
 *   ① 每份文件首行一句**书脊标签**，Otto 每轮只见全部标签（便宜）→ `spineIndex()`；
 *   ② 任务对上标签才把该文件**全文**装入本轮 → `matchKnowledge()`；
 *   ③ 用完不带入下一轮 —— 装配是**每轮现算**的纯函数，没有跨轮状态可带。
 */

/**
 * 一份知识文件的三种身份（`when:` 那一行决定）：
 *  · `always`    —— 常驻薄层，只有 `_core.md`，每轮必带；
 *  · `on-demand` —— 对上任一关键词就整份装入本轮（取用三规则②）；
 *  · `reference` —— **给人和机器读的参考件，永不进模型的上下文**。
 *
 * 第三种是本段落地时长出来的（登记在规格 §5）。③段建的两份手艺档
 * （`craft/seedance.md` / `craft/seedream.md`）自己写着「代码里的那几份仍是运行期权威，
 * 本文是给人读的同一份手艺」——把它们塞进 Otto 的上下文，等于把 `seedancePrompt` /
 * `seedreamPrompt` 两个 action 的 description 抄了第二份进说明书，正是这个仓库反复付
 * 学费的那种失同步；而且它们是给人读的华语长文，塞进英文说明书只是噪声。
 * 它们仍然在柜子里：书脊标签在册、`evals/checks/glossary.ts` 的镜头术语表照旧从
 * `craft/seedance.md` 解析取词 —— 只是不装进任何一轮。
 */
export type KnowledgeMode = "always" | "on-demand" | "reference";

/** 一格柜子：书脊标签、身份、装载关键词、全文（`knowledge-cabinet.generated.ts` 的行形状）。 */
export type KnowledgeFile = {
  readonly path: string;
  readonly spine: string;
  readonly mode: KnowledgeMode;
  readonly when: readonly string[];
  readonly text: string;
};

/** 常驻薄层的柜内路径。它的 `when` 是空表：不参与匹配，每轮必带。 */
export const CORE_PATH = "_core.md";

/**
 * 剥掉 `<!-- … -->` 注释块。
 *
 * 柜里的出处、机器可读的 `when` 行、给人读的旁注都写在注释里 —— 它们对维护的人有用，
 * 对模型只是噪声（还会把仓库路径抄进说明书，而 Otto 的铁律正是「你看不见代码」）。
 */
export function stripComments(markdown: string): string {
  if (/<!--(?:(?!-->)[\s\S])*$/.test(markdown)) throw new Error("有一个 <!-- 没有闭合");
  return markdown
    .replace(/<!--[\s\S]*?-->\n?/g, "")
    .replace(/\n{3,}/g, "\n\n")
    .replace(/\s+$/, "");
}

/** 装配顺序：柜内路径字典序，`_core.md` 永远第一（常驻薄层是整份说明书的开头）。 */
export function orderCabinetPaths(paths: readonly string[]): string[] {
  return [...paths].sort((a, b) =>
    a === CORE_PATH ? -1 : b === CORE_PATH ? 1 : a < b ? -1 : a > b ? 1 : 0,
  );
}

/**
 * 纯：一份 markdown → 一格柜子。缺书脊、缺 `when`、`when` 是空表 —— 三种都当场抛。
 *
 * fail closed 是有意的：一份没有关键词的文件永远装不进任何一轮，那是一份**看起来在教 Otto、
 * 实际上谁也读不到**的文件；这个仓库反复付学费的正是这一类「写了没人读」。
 */
export function parseCabinetFile(path: string, markdown: string): KnowledgeFile {
  const lines = markdown.split(/\r?\n/);
  const spine = /^#\s+(.+?)\s*$/.exec(lines[0] ?? "")?.[1];
  if (!spine) throw new Error(`${path}：第一行必须是书脊标签 \`# <一句话>\``);
  const when = /^<!--\s*when:\s*(.+?)\s*-->$/.exec(lines[1] ?? "")?.[1];
  if (!when) throw new Error(`${path}：第二行必须是 \`<!-- when: 关键词, … -->\``);
  const text = stripComments(markdown);
  if (path === CORE_PATH) {
    if (when.trim() !== "always") throw new Error(`${CORE_PATH} 是常驻薄层，when 只能是 always`);
    return { path, spine, mode: "always", when: [], text };
  }
  if (when.trim() === "always") {
    throw new Error(`${path}：只有 ${CORE_PATH} 可以是 always —— 别的文件都是按需装载`);
  }
  if (when.trim() === "reference") return { path, spine, mode: "reference", when: [], text };
  const keywords = when
    .split(",")
    .map((k) => k.trim().toLowerCase())
    .filter((k) => k.length > 0);
  if (keywords.length === 0) {
    throw new Error(`${path}：when 是空的 —— 没有关键词的文件永远装不进任何一轮`);
  }
  return { path, spine, mode: "on-demand", when: keywords, text };
}

const GENERATED_HEADER = `// AUTOGENERATED by scripts/gen-knowledge.ts — do not edit by hand.
// 改知识 = 改 packages/otto/knowledge/**.md，然后跑
//   pnpm --filter @fikirtive/otto run knowledge
// 为什么是 build 期常量而不是运行期读文件：见 scripts/gen-knowledge.ts 的文件头。
`;

/** 纯：柜子 → 生成模块的全文（书脊标签表 ＋ 全文常量表，§7.2⑥）。 */
export function renderCabinetModule(entries: readonly KnowledgeFile[]): string {
  const rows = entries
    .map(
      (e) =>
        `  {\n` +
        `    path: ${JSON.stringify(e.path)},\n` +
        `    spine: ${JSON.stringify(e.spine)},\n` +
        `    mode: ${JSON.stringify(e.mode)},\n` +
        `    when: ${JSON.stringify(e.when)},\n` +
        `    text: ${JSON.stringify(e.text)},\n` +
        `  },`,
    )
    .join("\n");
  return (
    GENERATED_HEADER +
    `import type { KnowledgeFile } from "./knowledge-cabinet.js";\n\n` +
    `/** 书脊标签表 ＋ 全文常量表，柜内路径字典序（\`${CORE_PATH}\` 第一）。 */\n` +
    `export const KNOWLEDGE_CABINET: readonly KnowledgeFile[] = [\n${rows}\n];\n`
  );
}

/**
 * 纯：全部**装得进某一轮**的书脊标签，每轮都进说明书（取用三规则①）。
 *
 * `reference` 件不在内 —— 告诉 Otto 一件他永远拿不到的知识存在，只会让他去承诺它。
 */
export function spineIndex(cabinet: readonly KnowledgeFile[]): string {
  return cabinet
    .filter((f) => f.mode === "on-demand")
    .map((f) => `- ${f.spine}`)
    .join("\n");
}

/** 纯：会进上下文的那些（常驻 ＋ 按需）。`reference` 件永不在内。 */
export function loadableFiles(cabinet: readonly KnowledgeFile[]): KnowledgeFile[] {
  return cabinet.filter((f) => f.mode !== "reference");
}

/**
 * 一个关键词命中没有：纯 ASCII 词按词边界匹配（`ad` 不该被 `already` 命中），
 * 带 CJK 的词按子串匹配（华语没有空格边界）。
 */
export function keywordHits(haystackLower: string, keyword: string): boolean {
  if (/^[a-z0-9]+(?: [a-z0-9]+)*$/.test(keyword)) {
    const escaped = keyword.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return new RegExp(`(?:^|[^a-z0-9])${escaped}(?:[^a-z0-9]|$)`).test(haystackLower);
  }
  return haystackLower.includes(keyword);
}

/**
 * 取用三规则②：本轮任务对上哪些书脊，就装哪几份全文。
 *
 * 返回的是**柜内路径**，顺序即装配顺序；`_core.md` 永远在里面（常驻）。匹配是确定性的
 * 纯函数：同一段话每次装出同一份说明书 —— 这正是⑥段能与③段的基线**对分**的前提。
 */
export function matchKnowledge(
  turnText: string,
  cabinet: readonly KnowledgeFile[],
): KnowledgeFile[] {
  const hay = turnText.toLowerCase();
  return cabinet.filter(
    (f) => f.mode === "always" || (f.mode === "on-demand" && f.when.some((k) => keywordHits(hay, k))),
  );
}
