export const PARITY_EXEMPTIONS = ["ADMIN", "VISUAL", "MONEY_IN", "ACCOUNT_SECURITY"] as const;

export type ParityExemption = (typeof PARITY_EXEMPTIONS)[number];

export type ParityManifestEntry =
  | { skill: string; reason?: string }
  | { exempt: ParityExemption; reason: string }
  | { todoSkill: true; reason: string };

export const PARITY_READ_SURFACES = [
  {
    key: "admin-v2.getAdminV2Data",
    file: "apps/web/lib/admin-v2.ts",
    exportName: "getAdminV2Data",
  },
] as const;

export const PARITY_MANIFEST = {
  "account-actions.getMyAccount": { todoSkill: true, reason: "Account credits/settings need a read skill or a reviewed ACCOUNT_SECURITY split." },
  "account-actions.signOutAction": { exempt: "ACCOUNT_SECURITY", reason: "Sign-out is an account-security action; Otto must not perform it." },
  "account-view-data.getAccountViewData": { todoSkill: true, reason: "Account overview needs read parity before hard parity debt is cleared." },
  "actions.getOrCreateDefaultProject": { todoSkill: true, reason: "Project bootstrap/read surface predates the manifest and needs project skill mapping." },
  "actions.createProject": { todoSkill: true, reason: "Manual project management needs a project-management skill before todoSkill can clear." },
  "actions.deleteProject": { todoSkill: true, reason: "Project deletion needs an Otto skill with the same guarded server action." },
  "actions.renameProject": { skill: "setTitle" },
  "actions.autoTitleProjectIfDefault": { skill: "setTitle" },
  "actions.createEntity": { skill: "describeRefs" },
  "actions.updateEntity": { skill: "describeRefs" },
  "actions.addEntityAlias": { skill: "describeRefs" },
  "actions.removeEntityAlias": { skill: "describeRefs" },
  "actions.softDeleteReferenceImage": { todoSkill: true, reason: "Reference-image lifecycle needs entity/reference skill parity." },
  "actions.addReferenceImages": { skill: "describeRefs" },
  "actions.softDeleteEntity": { todoSkill: true, reason: "Entity deletion needs explicit skill parity and approval semantics." },
  "actions.createShot": { skill: "proposeStoryboard" },
  "actions.saveShotPrompt": { todoSkill: true, reason: "Shot prompt editing needs an edit-storyboard skill; only proposeStoryboard exists today." },
  "actions.updateShotTitle": { skill: "setTitle" },
  "actions.updateShotStatus": { todoSkill: true, reason: "Shot workflow status needs storyboard-management skill parity." },
  "actions.softDeleteShot": { todoSkill: true, reason: "Shot deletion needs storyboard-management skill parity." },
  "actions.uploadCandidates": { todoSkill: true, reason: "Manual upload/import surfaces need reference-management skill parity." },
  "actions.uploadReference": { todoSkill: true, reason: "Manual reference upload needs reference-management skill parity." },
  "actions.attachGeneration": { todoSkill: true, reason: "Manual generation attachment needs canvas/storyboard skill parity." },
  "actions.detachGeneration": { todoSkill: true, reason: "Manual generation detachment needs canvas/storyboard skill parity." },
  "actions.deleteGeneration": { todoSkill: true, reason: "Generation deletion needs safe skill parity and paid-output warning semantics." },
  "actions.saveProjectEdit": { exempt: "VISUAL", reason: "Editor JSON is a visual timeline micro-operation; Otto parity belongs in higher-level edit skills." },
  "actions.addSegmentToCut": { exempt: "VISUAL", reason: "Cut segmentation is a visual editor micro-operation." },
  "actions.startRender": { todoSkill: true, reason: "Render/export needs a render skill or explicit visual exemption review." },
  "actions.getRenderJobs": { todoSkill: true, reason: "Render job reads need read-skill parity." },
  "actions.startCaption": { todoSkill: true, reason: "Caption generation needs a caption skill before parity debt clears." },
  "actions.getCaptionJob": { todoSkill: true, reason: "Caption job reads need read-skill parity." },
  "actions.getTranscript": { todoSkill: true, reason: "Transcript reads need read-skill parity and privacy review." },
  "actions.softDeleteGeneration": { todoSkill: true, reason: "Generation deletion needs safe skill parity and paid-output warning semantics." },
  "actions.getEditorMedia": { todoSkill: true, reason: "Editor media reads need read-skill parity." },
  "actions.loadMoreMedia": { todoSkill: true, reason: "Media pagination reads need read-skill parity." },
  "actions.recordGenerationOutcome": { todoSkill: true, reason: "Outcome recording needs analytics/feedback skill parity." },

  "admin-actions.saveModelDirective": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.seedResearchDirectives": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveRuntimeConfig": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveModelEnabled": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveUserRole": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-v2.getAdminV2Data": { exempt: "ADMIN", reason: "Admin v2 read model is City Hall and explicitly exempt from Otto control." },

  "analytics-actions.getAnalytics": { todoSkill: true, reason: "Analytics data needs a free/read Otto skill before parity debt clears." },
  "asset-actions.getGeneration": { todoSkill: true, reason: "Asset detail reads need read-skill parity." },
  "asset-actions.saveCroppedGeneration": { exempt: "VISUAL", reason: "Cropping is visual micro-manipulation; Otto parity belongs in higher-level edit skills." },
  "asset-actions.setFavorite": { todoSkill: true, reason: "Library preference mutation needs asset-management skill parity." },
  "billing-actions.listCreditPacks": { exempt: "MONEY_IN", reason: "Credit purchase/money-in surfaces are never delegated to Otto." },
  "billing-actions.createTopupCheckout": { exempt: "MONEY_IN", reason: "Credit purchase/money-in surfaces are never delegated to Otto." },

  "brand-actions.getBrandKit": { skill: "lookupProducts" },
  "brand-actions.saveBrandKit": { skill: "rememberBrandFact" },
  "brand-actions.listBrandRules": { skill: "lookupProducts" },
  "brand-actions.addBrandRule": { skill: "rememberBrandFact" },
  "brand-actions.setBrandRuleActive": { skill: "rememberBrandFact" },
  "brand-actions.deleteBrandRule": { skill: "rememberBrandFact" },
  "brand-record-actions.listMyBrandRecords": { skill: "lookupProducts" },
  "brand-record-actions.listBrandRecords": { skill: "lookupProducts" },
  "brand-record-actions.saveBrandRecord": { skill: "saveProduct" },
  "brand-record-actions.deleteBrandRecord": { todoSkill: true, reason: "Brand record deletion needs a matching brand-memory skill path." },
  "brand-record-actions.restoreBrandRecord": { todoSkill: true, reason: "Brand record restore needs a matching brand-memory skill path." },
  "brand-research.researchBrandFromUrl": { skill: "researchWeb" },

  "canvas-actions.listCanvasNodes": { todoSkill: true, reason: "Canvas read parity needs a canvas read/place skill." },
  "canvas-actions.createCanvasNode": { todoSkill: true, reason: "Canvas placement skill is planned but not registered yet." },
  "canvas-actions.moveCanvasNode": { exempt: "VISUAL", reason: "Pure canvas positioning is a visual micro-operation." },
  "canvas-actions.updateTextNode": { todoSkill: true, reason: "Canvas text edits need a canvas editing skill or a reviewed VISUAL exemption." },
  "canvas-actions.deleteCanvasNode": { todoSkill: true, reason: "Canvas deletion needs a canvas editing skill with paid-output warnings." },

  "cowork-actions.coworkDraftStoryboard": { skill: "proposeStoryboard" },
  "cowork-actions.enhancePrompt": { skill: "seedreamPrompt" },
  "cowork-actions.coworkTurn": { todoSkill: true, reason: "Legacy cowork turn is superseded by Otto but still exported; retire or map before clearing debt." },
  "cowork-actions.coworkGenerate": { skill: "generate" },
  "cowork-actions.coworkRenameThread": { skill: "setTitle" },
  "cowork-actions.coworkDeleteThread": { todoSkill: true, reason: "Thread deletion needs Otto thread-management parity." },
  "cowork-actions.coworkVaryCard": { skill: "propose" },
  "cowork-actions.setCoworkBrief": { skill: "updateBrief" },
  "cowork-actions.cancelGenJob": { todoSkill: true, reason: "Generation cancellation needs a guarded Otto/user action parity decision." },
  "cowork-fetch.getCoworkThreadClient": { todoSkill: true, reason: "Thread read surface needs free/read skill parity or retirement with cowork UI." },
  "credit-actions.grantCreditsAction": { exempt: "MONEY_IN", reason: "Admin credit grants mint money-in credits and Otto must not perform them." },

  "gen-actions.startGen": { skill: "generate" },
  "gen-actions.getActiveGenModels": { skill: "generate" },
  "gen-actions.getGenJob": { skill: "generate" },
  "gen-actions.getRecentGenResults": { skill: "generate" },
  "library-actions.getGenerationHistory": { todoSkill: true, reason: "Library/history read needs free/read skill parity." },

  "memory-actions.listMyMemory": { skill: "lookupProducts" },
  "memory-actions.listMemory": { skill: "lookupProducts" },
  "memory-actions.addMemory": { skill: "rememberBrandFact" },
  "memory-actions.updateMemory": { skill: "rememberBrandFact" },
  "memory-actions.deleteMemory": { skill: "rememberBrandFact" },
  "memory-actions.getBrandContextText": { skill: "lookupProducts" },

  "meta-actions.completeMetaConnect": { exempt: "ACCOUNT_SECURITY", reason: "OAuth connection binding is an account-security action." },
  "meta-actions.getMetaConnection": { skill: "meta-list-objects" },
  "meta-actions.disconnectMeta": { exempt: "ACCOUNT_SECURITY", reason: "Disconnecting an external account is account security." },
  "meta-actions.getMetaInsights": { skill: "meta-insights" },
  "meta-build-actions.runAdBuild": { skill: "propose-ad-build" },
  "meta-build-actions.approveAdBuild": { skill: "propose-ad-build" },
  "meta-build-actions.launchAdDraft": { skill: "propose-ad-build" },
  "meta-build-actions.maybeAutoBuild": { skill: "propose-ad-build" },
  "meta-build-propose.proposeAdBuildForOwner": { skill: "propose-ad-build" },
  "meta-insights.fetchOwnerInsights": { skill: "meta-insights" },
  "meta-insights.fetchOwnerInsightsSeries": { skill: "meta-insights" },
  "meta-objects.fetchOwnerAdAccounts": { skill: "meta-list-objects" },
  "meta-objects.fetchOwnerAdObjects": { skill: "meta-list-objects" },
  "meta-pages.fetchOwnerPages": { skill: "list-meta-pages" },
  "meta-propose.proposeMetaActionForOwner": { skill: "propose-meta-action" },
  "meta-write-actions.setAdsAutonomy": { skill: "propose-meta-action" },
  "meta-write-actions.setAdsWritesPaused": { skill: "propose-meta-action" },
  "meta-write-actions.runApprovedPlan": { skill: "propose-meta-action" },
  "meta-write-actions.approveMetaActionPlan": { skill: "propose-meta-action" },
  "meta-write-actions.maybeAutoRun": { skill: "propose-meta-action" },

  "otto-actions.buildOttoContext": { todoSkill: true, reason: "Internal Otto context builder is exported from an action file; review before making scanner narrower." },
  "otto-actions.finalizeOttoRun": { todoSkill: true, reason: "Internal Otto finalizer is exported from an action file; review before making scanner narrower." },
  "otto-actions.ottoTurn": { todoSkill: true, reason: "Otto turn is the agent loop itself, not a single skill; needs a manifest convention." },
  "otto-actions.ottoApprove": { todoSkill: true, reason: "Otto approval dispatch spans card kinds; needs per-card action parity mapping." },
  "otto-actions.createEmptyCoworkThread": { todoSkill: true, reason: "Thread creation needs thread-management parity." },
  "otto-actions.deleteCoworkThread": { todoSkill: true, reason: "Thread deletion needs thread-management parity." },
  "otto-canvas-bridge.syncOttoCanvasNodes": { todoSkill: true, reason: "Canvas bridge read/write sync needs canvas skill parity." },
  "otto-client-actions.ottoTurn": { todoSkill: true, reason: "Client wrapper for Otto turn; underlying action needs a manifest convention." },
  "otto-client-actions.ottoApprove": { todoSkill: true, reason: "Client wrapper for Otto approval; underlying action needs per-card parity mapping." },
  "otto-client-actions.createEmptyCoworkThread": { todoSkill: true, reason: "Client wrapper for thread creation needs thread-management parity." },
  "otto-client-actions.deleteCoworkThread": { todoSkill: true, reason: "Client wrapper for thread deletion needs thread-management parity." },
  "otto-client-actions.approveMetaActionPlan": { skill: "propose-meta-action" },
  "otto-client-actions.approveAdBuild": { skill: "propose-ad-build" },
  "otto-client-actions.launchAdDraft": { skill: "propose-ad-build" },
  "otto-client-actions.setAdsAutonomy": { skill: "propose-meta-action" },
  "otto-client-actions.setAdsWritesPaused": { skill: "propose-meta-action" },
  "owner-settings-actions.getOwnerSettings": { todoSkill: true, reason: "Owner Otto behavior settings need read parity or account-security split." },
  "owner-settings-actions.setOwnerSetting": { todoSkill: true, reason: "Owner Otto behavior setting mutations need skill parity or account-security split." },

  "refgen-actions.startRefGen": { skill: "describeRefs" },
  "refgen-actions.setBaseAsset": { skill: "describeRefs" },
  "refgen-actions.createVariant": { skill: "describeRefs" },
  "refgen-actions.regenerateVariant": { skill: "describeRefs" },
  "refgen-actions.renameVariant": { skill: "describeRefs" },
  "refgen-actions.deleteVariant": { todoSkill: true, reason: "Reference variant deletion needs a guarded reference skill path." },
  "refgen-actions.getRefGenJobs": { skill: "describeRefs" },
  "research-actions.getResearchCard": { skill: "proposeResearch" },
  "research-actions.approveResearch": { skill: "researchWeb" },
  "storyboard-actions.editShotPrompt": { todoSkill: true, reason: "Edit-storyboard skill is named in the design but not registered yet." },
  "storyboard-actions.addShot": { skill: "proposeStoryboard" },
  "storyboard-actions.deleteShot": { todoSkill: true, reason: "Storyboard deletion needs edit-storyboard skill parity." },
  "storyboard-actions.reorderShots": { todoSkill: true, reason: "Storyboard ordering is a visual/storyboard micro-operation pending skill convention." },
  "storyboard-gate1-actions.getStoryboardVideoOptions": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.prepareStoryboardFirstFrames": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.regenShotFirstFrameCard": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.syncStoryboardMedia": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.prepareStoryboardVideos": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.regenShotVideoCard": { skill: "proposeStoryboard" },
  "studio-actions.addShot": { skill: "proposeStoryboard" },
  "studio-actions.deleteShot": { todoSkill: true, reason: "Studio shot deletion needs edit-storyboard skill parity." },
  "studio-actions.moveShot": { todoSkill: true, reason: "Studio shot ordering needs edit-storyboard skill parity." },
  "studio-actions.addScene": { skill: "proposeStoryboard" },
  "studio-actions.setShotPromptText": { todoSkill: true, reason: "Studio prompt editing needs edit-storyboard skill parity." },
  "studio-actions.setShotFrame": { skill: "proposeStoryboard" },
  "studio-actions.setShotTransition": { skill: "proposeStoryboard" },

  "tenant-actions.setMembershipStatus": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.cutTenantSessions": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.inviteTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.revokeTenantInvite": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.impersonateTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.stopImpersonatingTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.grantTenantCredits": { exempt: "MONEY_IN", reason: "Admin credit grants mint money-in credits and Otto must not perform them." },
  "thread-activity.listProjectThreadActivity": { todoSkill: true, reason: "Thread activity read needs free/read skill parity." },
  "upload-actions.authorizeUpload": { todoSkill: true, reason: "Upload authorization needs media/import skill parity or account-security review." },
  "upload-actions.uploadFileFallback": { todoSkill: true, reason: "Upload fallback needs media/import skill parity." },
  "upload-actions.signUploadPart": { todoSkill: true, reason: "Multipart upload signing needs media/import skill parity or account-security review." },
  "upload-actions.abortDirectUpload": { todoSkill: true, reason: "Upload cancellation needs media/import skill parity." },
  "upload-actions.finalizeCandidateUploads": { todoSkill: true, reason: "Upload finalization needs media/import skill parity." },

  "api:better-auth/[...all].GET": { exempt: "ACCOUNT_SECURITY", reason: "Better Auth routes are account-security surfaces." },
  "api:better-auth/[...all].POST": { exempt: "ACCOUNT_SECURITY", reason: "Better Auth routes are account-security surfaces." },
  "api:meta/authorize.GET": { exempt: "ACCOUNT_SECURITY", reason: "OAuth authorization starts external account binding." },
  "api:meta/callback.GET": { exempt: "ACCOUNT_SECURITY", reason: "OAuth callback binds external accounts and must stay human-controlled." },
  "api:otto/stream.POST": { todoSkill: true, reason: "Otto stream is the agent transport; needs a manifest convention separate from individual skills." },
  "api:stripe/webhook.POST": { exempt: "MONEY_IN", reason: "Stripe webhook is money-in and authenticated by Stripe signature, not Otto." },
} as const satisfies Record<string, ParityManifestEntry>;
