/**
 * parity-manifest.ts — the 9th expansion seam (BLUEPRINT §四 / docs/design/2026-07-03-harmony-02).
 *
 * A machine- and human-readable table: every human server action ↔ the Otto skill that exposes the
 * same capability, an explicit exemption (four closed classes), or a TODO_SKILL debt entry (an
 * action that SHOULD get a skill but doesn't yet — 欠账清单, not an exemption). This turns 宪法 7
 * ("Otto can operate 100% of what a human can") from prose into structure.
 *
 * STATUS — rollout per harmony-02 §四: this is the initial SEED, registering the Schedule,
 * P1-01 product-ingest, and P-block Meta performance surfaces. Full backfill of every existing
 * action (盘点回填) and the CI enforcer (scripts/check-parity.sh, warn→hard) are separate follow-ups.
 * Keep this a PURE LITERAL (SECTION_MATRIX style) so a diff is one-glance auditable. A new
 * exemption class = a constitution amendment (founder-approved).
 */
export const PARITY_EXEMPTIONS = ["ADMIN", "VISUAL", "MONEY_IN", "ACCOUNT_SECURITY"] as const;

export type ParityExemption = (typeof PARITY_EXEMPTIONS)[number];

export type ParityManifestEntry =
  | { skill: string; reason?: string }
  | { exempt: ParityExemption; reason: string }
  | { todoSkill: true; reason: string };

export const PARITY_READ_SURFACES = [
  {
    key: "admin-v2.getAdminV2Data",
    file: "apps/web/lib/admin-v2.ts",
    exportName: "getAdminV2Data",
  },
  {
    key: "data.getProjects",
    file: "apps/web/lib/data.ts",
    exportName: "getProjects",
  },
  {
    key: "data.getEntities",
    file: "apps/web/lib/data.ts",
    exportName: "getEntities",
  },
  {
    key: "data.getCoworkThreads",
    file: "apps/web/lib/data.ts",
    exportName: "getCoworkThreads",
  },
  {
    key: "data.getCoworkThread",
    file: "apps/web/lib/data.ts",
    exportName: "getCoworkThread",
  },
  {
    key: "data.resolveCoworkResultUrls",
    file: "apps/web/lib/data.ts",
    exportName: "resolveCoworkResultUrls",
  },
  {
    key: "data.getMyAds",
    file: "apps/web/lib/data.ts",
    exportName: "getMyAds",
  },
  {
    key: "data.getMyAdJobs",
    file: "apps/web/lib/data.ts",
    exportName: "getMyAdJobs",
  },
  {
    key: "data.getRecentGenerationThumbs",
    file: "apps/web/lib/data.ts",
    exportName: "getRecentGenerationThumbs",
  },
  {
    key: "data.getAllCoworkThreadMetas",
    file: "apps/web/lib/data.ts",
    exportName: "getAllCoworkThreadMetas",
  },
] as const;

export const PARITY_MANIFEST = {
  "account-actions.getMyAccount": { todoSkill: true, reason: "Account credits/settings need a read skill or a reviewed ACCOUNT_SECURITY split." },
  "account-actions.signOutAction": { exempt: "ACCOUNT_SECURITY", reason: "Sign-out is an account-security action; Otto must not perform it." },
  "account-view-data.getAccountViewData": { todoSkill: true, reason: "Account overview needs read parity before hard parity debt is cleared." },
  "actions.getOrCreateDefaultProject": { skill: "manageProjects" },
  "actions.createProject": { skill: "manageProjects" },
  "actions.deleteProject": { skill: "manageProjects", reason: "Parity via ctx.projects; PERMANENT delete goes through the SAME guarded owner-scoped action (refuses while a generation runs, refunds queued jobs)." },
  "actions.renameProject": { skill: "manageProjects", reason: "Real project rename (Project.name) via ctx.projects — distinct from setTitle, which renames the chat (ChatThread.title)." },
  "actions.setProjectPinned": { skill: "manageProjects" },
  "actions.autoTitleProjectIfDefault": { skill: "setTitle" },
  "actions.createEntity": { skill: "manageEntities", reason: "Real entity creation (name+type) via ctx.entities — distinct from describeRefs, which annotates an existing entity. Uploading photos stays a human file action." },
  "actions.updateEntity": { skill: "describeRefs" },
  "actions.addEntityAlias": { skill: "describeRefs" },
  "actions.removeEntityAlias": { skill: "describeRefs" },
  "actions.softDeleteReferenceImage": { skill: "manageEntities" },
  "actions.addReferenceImages": { skill: "describeRefs" },
  "actions.softDeleteEntity": { skill: "manageEntities", reason: "Soft-delete via ctx.entities (reversible tombstone; history/snapshots stay intact)." },
  "actions.createShot": { skill: "proposeStoryboard" },
  "actions.saveShotPrompt": { skill: "editStoryboard", reason: "Capability-level parity (same convention as createShot→proposeStoryboard): the legacy Shot composer's prompt editing is covered by editStoryboard's op=editShot on the STORYBOARD_CARD path; the legacy Shot-model surface itself is slated for retire (L-C §七.D6)." },
  "actions.updateShotTitle": { skill: "setTitle" },
  "actions.updateShotStatus": { skill: "editStoryboard", reason: "Capability-level parity: the legacy Shot status workflow (draft→ready) is subsumed by card-payload editing on the STORYBOARD_CARD path (a card shot's readiness is its prompts/pointers, not a status enum); legacy Shot-model surface slated for retire (L-C §七.D6)." },
  "actions.softDeleteShot": { skill: "editStoryboard", reason: "Capability-level parity (same convention as createShot→proposeStoryboard): shot deletion is editStoryboard's op=deleteShot on the STORYBOARD_CARD path; legacy Shot-model surface slated for retire (L-C §七.D6)." },
  "actions.uploadCandidates": { skill: "importMedia", reason: "W-B3-B (E1-17): legacy browser-form candidate upload; importMedia provides the SAME media-import capability server-side (URL -> Generation source:UPLOAD)." },
  "actions.uploadReference": { skill: "importMedia", reason: "W-B3-B (E1-17): legacy browser-form reference upload; importMedia provides the SAME media-import capability (URL -> Generation source:UPLOAD)." },
  "actions.attachGeneration": { skill: "manageMedia", reason: "W-B3-B (B0-12): manageMedia.attach goes through this same owner-scoped action via ctx.media.attach." },
  "actions.detachGeneration": { skill: "manageMedia", reason: "W-B3-B (B0-12): manageMedia.detach goes through this same action via ctx.media.detach." },
  "actions.deleteGeneration": { skill: "manageMedia", reason: "W-B3-B (B0-12): manageMedia.delete soft-deletes via ctx.media.remove -> this same action (reversible tombstone; no model self-confirm)." },
  "actions.saveProjectEdit": { exempt: "VISUAL", reason: "Editor JSON is a visual timeline micro-operation; Otto parity belongs in higher-level edit skills." },
  "actions.addSegmentToCut": { exempt: "VISUAL", reason: "Cut segmentation is a visual editor micro-operation." },
  "actions.startRender": { skill: "renderVideo", reason: "W-B3-B (B0-13): renderVideo.export renders the SAVED cut through this same $0 action (ctx.render.export)." },
  "actions.getRenderJobs": { skill: "renderVideo", reason: "W-B3-B (B0-13): renderVideo reads render status via ctx.render.jobs -> this same action." },
  "actions.startCaption": { skill: "renderVideo", reason: "W-B3-B (B0-13): renderVideo.caption dispatches $0 whisper captions via ctx.render.caption -> this same action." },
  "actions.getCaptionJob": { skill: "renderVideo", reason: "W-B3-B (B0-13): renderVideo reads caption status via ctx.render.captionJob -> this same action." },
  "actions.getTranscript": { skill: "renderVideo", reason: "W-B3-B (B0-13): renderVideo reads the cached transcript via ctx.render.transcript -> this same action." },
  "actions.softDeleteGeneration": { skill: "manageMedia", reason: "W-B3-B (B0-12): manageMedia.discard soft-deletes from the candidate zone via ctx.media.discard -> this same action." },
  "actions.getEditorMedia": { skill: "manageMedia", reason: "W-B3-B (B0-14): manageMedia.list reads project media via ctx.media.list -> this same action." },
  "actions.loadMoreMedia": { skill: "manageMedia", reason: "W-B3-B (B0-14): manageMedia.load_more pages the library via ctx.media.loadMore -> this same action." },
  "actions.recordGenerationOutcome": { todoSkill: true, reason: "Outcome recording needs analytics/feedback skill parity." },

  "admin-actions.saveModelDirective": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.seedResearchDirectives": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveRuntimeConfig": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveModelEnabled": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-actions.saveUserRole": { exempt: "ADMIN", reason: "City Hall admin is a permanent blueprint exemption." },
  "admin-v2.getAdminV2Data": { exempt: "ADMIN", reason: "Admin v2 read model is City Hall and explicitly exempt from Otto control." },

  "analytics-actions.getAnalytics": { todoSkill: true, reason: "Analytics data needs a free/read Otto skill before parity debt clears." },
  "asset-actions.getGeneration": { skill: "manageLibrary" },
  "asset-actions.saveCroppedGeneration": { exempt: "VISUAL", reason: "Cropping is visual micro-manipulation; Otto parity belongs in higher-level edit skills." },
  "asset-actions.setFavorite": { skill: "manageLibrary" },
  "billing-actions.listCreditPacks": { exempt: "MONEY_IN", reason: "Credit purchase/money-in surfaces are never delegated to Otto." },
  "billing-actions.createTopupCheckout": { exempt: "MONEY_IN", reason: "Credit purchase/money-in surfaces are never delegated to Otto." },

  "brand-record-actions.listMyBrandRecords": { skill: "lookupProducts" },
  "brand-record-actions.listBrandRecords": { skill: "lookupProducts" },
  "brand-record-actions.saveBrandRecord": { skill: "saveProduct" },
  "brand-record-actions.deleteBrandRecord": { skill: "manageBrandMemory" },
  "brand-record-actions.restoreBrandRecord": { skill: "manageBrandMemory" },
  "product-ingest-actions.ingestProductFromUrl": { skill: "ingestProduct" },

  "campaign-actions.proposeCampaign": { skill: "planCampaign", reason: "B0-51/53/C2a: structured Campaign creation uses a server-issued owner-bound id and the same zero-cost action as the workbench." },
  "campaign-actions.proposeCampaignEntry": { skill: "planCampaign", reason: "B0-54/56/C2a: structured CAMPAIGN_CARD proposal uses a server-issued owner-bound entry id; estCredits remains display-only." },
  "campaign-actions.updateCampaignEntry": { skill: "planCampaign", reason: "B0-54/56/C2a: entry edits use the same owner-scoped optimistic action as the Campaign UI." },
  "campaign-actions.removeCampaignEntry": { skill: "planCampaign", reason: "B0-54/56/C2a: entry removal is an internal planJson edit through the shared action." },
  "campaign-actions.approveCampaignEntry": { skill: "planCampaign", reason: "B0-56/C2a: approval marks only entry-level plan status; it never dispatches generation, spend, send, or publish." },
  "campaign-actions.setCampaignGrouping": { skill: "planCampaign", reason: "B0-52/C2a: Project/ScheduledPost/Generation grouping validates both Campaign and target against the authenticated owner." },
  "campaign-view-data.listCampaigns": { skill: "readCampaigns", reason: "B0-55/C2a read parity: owner-scoped Campaign list and structured plan summaries." },
  "campaign-view-data.getCampaign": { skill: "readCampaigns", reason: "B0-52/55/C2a read parity: exact owner-scoped Campaign detail with independently owner-scoped grouped summaries." },
  "campaign-generation-confirm.quoteCampaignGeneration": { todoSkill: true, reason: "B0-57/C2b human-only pack-confirm UI (issue #395, debt-110): $0 owner-scoped server-recompute of the approved-plan price from the live config; the Otto planCampaign/generate skill is staged for a later Founder-approved milestone per the B8 §7.2 contract." },
  "campaign-generation-confirm.confirmCampaignGeneration": { todoSkill: true, reason: "B0-57/C2b human-only pack-confirm UI (issue #395, debt-111): owner-only batch generation confirm; adds NO spend path — it reuses the existing orchestrateBatch→startGen authority (per-cell reserve/settle/refund). Otto generate skill staged for a later Founder-approved milestone per B8 §7.2." },

  "crm-actions.createContact": { skill: "manageContacts", reason: "B0-59/C1 act parity: creates only an owner-scoped Contact and returns deterministic duplicate suggestions; identity and consent are never inferred." },
  "crm-actions.setContactConsent": { skill: "manageContacts", reason: "B0-60/C1 act parity: manual consent capture enters the shared ConsentEvent runtime as crm_manual merchant/backfill/asserted." },
  "crm-actions.updateContact": { skill: "manageContacts", reason: "B0-60/C1 act parity: standard name/lifecycle edits use the same bounded owner-scoped action; receipt, identity, consent, and DND fields are excluded." },
  "crm-actions.setContactDnd": { skill: "manageContacts", reason: "B0-60/C1 act parity: the human toggle enters ContactDndEvent through the shared crm_ui writer." },
  "crm-actions.setContactDndFromOtto": { skill: "manageContacts", reason: "B0-60/C1 act parity: Otto DND changes use the same action boundary and engine with otto_approved_action provenance." },
  "crm-actions.importContacts": { skill: "manageContacts", reason: "B0-59/C1 act parity: bounded CSV import creates owner-scoped Contact rows, returns suggestions only, and routes optional consent through sourceKind import." },
  "crm-view-data.listContacts": { skill: "readContacts", reason: "B0-59/60/C1 read parity: owner-scoped Contact list reads WhatsApp × marketing ConsentStateProjection and DND." },
  "crm-view-data.getContact": { skill: "readContacts", reason: "B0-60/C1 read parity: exact owner-scoped profile includes read-only identities and newest-first ConsentEvent history." },
  "crm-view-data.searchContacts": { skill: "readContacts", reason: "B0-59/C1 read parity: owner-scoped name/identity search with optional lifecycle filter." },

  "customer-inbox-ui-actions.listConversations": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.getConversation": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.searchConversations": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.getHistory": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.getConversationPreflight": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.listTemplates": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.saveConversationDraft": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.assignConversation": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.takeOverConversation": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.handOffConversation": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.setConversationStatus": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.requestAutomationResume": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.createMessageTemplate": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },
  "customer-inbox-ui-actions.createMessageTemplateVersion": { todoSkill: true, reason: "C4b-M3 human-only Inbox UI (issue #378); Otto Inbox skill is staged for a later Founder-approved milestone per the C4a contract (spec §6/§10)." },

  "customer-broadcast-ui-actions.listBroadcastRuns": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.getBroadcastRun": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.getBroadcastRunLivePreflight": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.previewAudienceEligibility": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.createBroadcastRun": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.freezeAudience": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.confirmBroadcastRun": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.cancelBroadcastRun": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },
  "customer-broadcast-ui-actions.executeBroadcastRun": { todoSkill: true, reason: "C5-M3 human-only broadcast workbench UI (issue #388): SIMULATED execution (zero real provider/spend); Otto Broadcast skill is staged for a later Founder-approved milestone per the C5 contract (spec §6/§10)." },

  "canvas-actions.listCanvasNodes": { skill: "manageCanvas" },
  "canvas-actions.createCanvasNode": { skill: "manageCanvas" },
  "canvas-actions.moveCanvasNode": { exempt: "VISUAL", reason: "Pure canvas positioning is a visual micro-operation." },
  "canvas-actions.updateTextNode": { skill: "manageCanvas" },
  "canvas-actions.resolveCanvasNode": { skill: "manageCanvas" },
  "canvas-actions.deleteCanvasNode": { skill: "manageCanvas", reason: "Parity = settled nodes; in-flight paid cards are UI-only removals (the skill hard-refuses, fail-closed pre-check)." },

  "cowork-actions.coworkGenerate": { skill: "generate" },
  "cowork-actions.coworkRenameThread": { skill: "setTitle" },
  "cowork-actions.coworkDeleteThread": { todoSkill: true, reason: "Thread deletion needs Otto thread-management parity." },
  "cowork-actions.coworkVaryCard": { skill: "propose" },
  "cowork-actions.setCoworkBrief": { skill: "updateBrief" },
  "cowork-actions.cancelGenJob": { skill: "manageMedia", reason: "W-B3-B (debt-39): manageMedia.cancel_job cancels a still-QUEUED job via ctx.media.cancelJob -> this same action (refund-only, never charges)." },
  "cowork-fetch.getCoworkThreadClient": { todoSkill: true, reason: "Thread read surface needs free/read skill parity or retirement with cowork UI." },
  "credit-actions.grantCreditsAction": { exempt: "MONEY_IN", reason: "Admin credit grants mint money-in credits and Otto must not perform them." },

  "data.getProjects": { todoSkill: true, reason: "Otto home project list is page data; project reads need free/read skill parity." },
  "data.getEntities": { todoSkill: true, reason: "Otto home entity/reference list is page data; entity reads need free/read skill parity." },
  "data.getCoworkThreads": { todoSkill: true, reason: "Otto home thread list is page data; thread reads need free/read skill parity." },
  "data.getCoworkThread": { todoSkill: true, reason: "Otto home active-thread detail is page data; thread reads need free/read skill parity." },
  "data.resolveCoworkResultUrls": { todoSkill: true, reason: "Otto home result URL resolution is page data; generation result reads need free/read skill parity." },
  "data.getMyAds": { todoSkill: true, reason: "Otto home Library ads list is page data; finished ad reads need free/read skill parity." },
  "data.getMyAdJobs": { todoSkill: true, reason: "Otto home in-flight ad jobs are page data; generation status reads need free/read skill parity." },
  "data.getRecentGenerationThumbs": { todoSkill: true, reason: "Otto home history strip is page data; recent generation reads need free/read skill parity." },
  "data.getAllCoworkThreadMetas": { todoSkill: true, reason: "Otto home global sidebar threads are page data; thread reads need free/read skill parity." },

  "gen-actions.startGen": { skill: "generate" },
  "gen-actions.startCanvasGen": { skill: "generate", reason: "Canvas supplies a server-derived once-ever action key, then delegates to this same generate/startGen reserve and dispatch authority; it is not a second spend path." },
  "gen-actions.startCoworkGen": { skill: "generate", reason: "Otto's approved GEN_CARD supplies the server-bound owner/thread/project quote, then delegates to the same generate/startGen reserve and dispatch authority; it is not a second spend path." },
  "gen-actions.getActiveGenModels": { skill: "generate" },
  "gen-actions.getGenJob": { skill: "generate" },
  "gen-actions.getRecentGenResults": { skill: "generate" },
  "factory-actions.runVariantBatch": { skill: "runFactoryBatch", reason: "W-B3-F-P (B3 §5.2): variant fan-out batch; the runFactoryBatch skill (mode:variant) routes through this SAME owner-scoped action, which loops startGen per cell — zero new spend path." },
  "factory-actions.runBulkGrid": { skill: "runFactoryBatch", reason: "W-B3-F-P (B3 §5.2): bulk grid batch; the runFactoryBatch skill (mode:grid) routes through this SAME owner-scoped action, which loops startGen per cell — zero new spend path." },
  "library-actions.getGenerationHistory": { skill: "manageLibrary" },

  "memory-actions.listMyMemory": { skill: "lookupProducts" },
  "memory-actions.listMemory": { skill: "lookupProducts" },
  "memory-actions.addMemory": { skill: "rememberBrandFact" },
  "memory-actions.updateMemory": { skill: "rememberBrandFact" },
  "memory-actions.deleteMemory": { skill: "manageBrandMemory", reason: "Real memory soft-delete via ctx.brandMemory — distinct from rememberBrandFact, which adds/updates." },
  "memory-actions.getBrandContextText": { skill: "lookupProducts" },

  "meta-actions.completeMetaConnect": { exempt: "ACCOUNT_SECURITY", reason: "OAuth connection binding is an account-security action." },
  "meta-actions.getMetaConnection": { skill: "meta-list-objects" },
  "meta-actions.disconnectMeta": { exempt: "ACCOUNT_SECURITY", reason: "Disconnecting an external account is account security." },
  "meta-actions.getMetaInsights": { skill: "meta-insights" },
  "meta-performance-actions.getAdPerformance": { skill: "meta-ad-performance" },
  "meta-build-actions.runAdBuild": { skill: "propose-ad-build" },
  "meta-build-actions.approveAdBuild": { skill: "propose-ad-build" },
  "meta-build-actions.launchAdDraft": { skill: "propose-ad-build" },
  "meta-build-actions.maybeAutoBuild": { skill: "propose-ad-build" },
  "meta-build-propose.proposeAdBuildForOwner": { skill: "propose-ad-build" },
  "meta-insights.fetchOwnerInsights": { skill: "meta-insights" },
  "meta-insights.fetchOwnerInsightsSeries": { skill: "meta-insights" },
  "meta-objects.fetchOwnerAdAccounts": { skill: "meta-list-objects" },
  "meta-objects.fetchOwnerAdObjects": { skill: "meta-list-objects" },
  "meta-pages.fetchOwnerPages": { skill: "list-meta-pages" },
  "meta-propose.proposeMetaActionForOwner": { skill: "propose-meta-action" },
  "meta-write-actions.setAdsAutonomy": { skill: "propose-meta-action" },
  "meta-write-actions.setAdsWritesPaused": { skill: "propose-meta-action" },
  "meta-write-actions.runApprovedPlan": { skill: "propose-meta-action" },
  "meta-write-actions.approveMetaActionPlan": { skill: "propose-meta-action" },
  "meta-write-actions.maybeAutoRun": { skill: "propose-meta-action" },

  "otto-actions.buildOttoContext": { todoSkill: true, reason: "Internal Otto context builder is exported from an action file; review before making scanner narrower." },
  "otto-actions.finalizeOttoRun": { todoSkill: true, reason: "Internal Otto finalizer is exported from an action file; review before making scanner narrower." },
  "otto-actions.validateOttoTurnReferences": { todoSkill: true, reason: "Internal Otto turn reference validator shared by stream/non-stream routes; not a user operation." },
  "otto-actions.ottoTurn": { todoSkill: true, reason: "Otto turn is the agent loop itself, not a single skill; needs a manifest convention." },
  "otto-actions.ottoApprove": { todoSkill: true, reason: "Otto approval dispatch spans card kinds; needs per-card action parity mapping." },
  "otto-actions.ottoReject": { todoSkill: true, reason: "Approval-card decline dispatch (B4 debt-70 universal chain; static decline, zero LLM) — same per-card parity-mapping convention question as ottoApprove." },
  "otto-actions.createEmptyCoworkThread": { todoSkill: true, reason: "Thread creation needs thread-management parity." },
  "otto-actions.deleteCoworkThread": { todoSkill: true, reason: "Thread deletion needs thread-management parity." },
  "otto-actions.setCoworkThreadPinned": { todoSkill: true, reason: "Thread pinning needs thread-management parity." },
  "otto-canvas-bridge.syncOttoCanvasNodes": { skill: "manageCanvas", reason: "view = display-only sync + list; the bridge never spends." },
  "otto-client-actions.ottoTurn": { todoSkill: true, reason: "Client wrapper for Otto turn; underlying action needs a manifest convention." },
  "otto-client-actions.ottoApprove": { todoSkill: true, reason: "Client wrapper for Otto approval; underlying action needs per-card parity mapping." },
  "otto-client-actions.ottoReject": { todoSkill: true, reason: "Client wrapper for approval-card decline; underlying action needs per-card parity mapping." },
  "otto-client-actions.createEmptyCoworkThread": { todoSkill: true, reason: "Client wrapper for thread creation needs thread-management parity." },
  "otto-client-actions.deleteCoworkThread": { todoSkill: true, reason: "Client wrapper for thread deletion needs thread-management parity." },
  "otto-client-actions.renameCoworkThread": { skill: "setTitle" },
  "otto-client-actions.setCoworkThreadPinned": { todoSkill: true, reason: "Client wrapper for thread pinning needs thread-management parity." },
  "otto-client-actions.approveMetaActionPlan": { skill: "propose-meta-action" },
  "otto-client-actions.approveAdBuild": { skill: "propose-ad-build" },
  "otto-client-actions.launchAdDraft": { skill: "propose-ad-build" },
  "otto-client-actions.setAdsAutonomy": { skill: "propose-meta-action" },
  "otto-client-actions.setAdsWritesPaused": { skill: "propose-meta-action" },
  "owner-settings-actions.getOwnerSettings": { todoSkill: true, reason: "Owner Otto behavior settings need read parity or account-security split." },
  "owner-settings-actions.setOwnerSetting": { todoSkill: true, reason: "Owner Otto behavior setting mutations need skill parity or account-security split." },

  "refgen-actions.startRefGen": { skill: "generateReferences", reason: "debt-68 (B3 §5.2 W-B3-G-P): real refgen spend skill — cost:spend ⇒ needsApproval machine-derived literal true; goes through the SAME owner-scoped startRefGen authority via ctx.refgen (server-priced, per-entity dedup). Zero second spend source; supersedes the prior fake describeRefs mapping." },
  "refgen-actions.setBaseAsset": { skill: "describeRefs" },
  "refgen-actions.createVariant": { skill: "describeRefs" },
  "refgen-actions.regenerateVariant": { skill: "describeRefs" },
  "refgen-actions.renameVariant": { skill: "describeRefs" },
  "refgen-actions.deleteVariant": { skill: "deleteReferenceVariant", reason: "debt-69 (B3 §5.2 W-B3-G-P): guarded $0 delete skill — same owner-scoped deleteVariant authority via ctx.refgen; the port fail-closed refuses while a paid RefGenJob for the variant is in flight (#271 deleteProject precedent)." },
  "refgen-actions.getRefGenJobs": { skill: "describeRefs" },
  "research-actions.getResearchCard": { skill: "proposeResearch" },
  "research-actions.approveResearch": { skill: "researchWeb" },
  "segment-actions.listSegments": { skill: "readSegments", reason: "B0-61/C3 read parity: lists owner-scoped CRM Segments with structured rules and live counts through the same authenticated action." },
  "segment-actions.getSegment": { skill: "readSegments", reason: "B0-61/C3 read parity: reads one exact owner-scoped CRM Segment and its live counts through the same authenticated action." },
  "segment-actions.previewSegment": { skill: "readSegments", reason: "B0-61/C3 preview parity: evaluates the same structured rule object through the shared deterministic validator and owner-scoped contact reader." },
  "segment-actions.buildSegment": { skill: "buildSegment", reason: "B0-61/C3 act parity: create/update both use the same authenticated validator; create keeps the server-issued signed ULID retry fence and update is owner-scoped." },
  "trend-actions.listTrendSnapshots": { skill: "readCampaigns", reason: "B0-58/C2a read parity: source-labelled owner-scoped Trend conclusions through the same archive action." },
  "trend-actions.saveTrendSnapshot": { skill: "planCampaign", reason: "B0-58/C2a act parity: server-issued retry-safe Trend snapshot write; optional Campaign link is validated against the same authenticated owner." },
  "schedule-service.draftScheduledPost": { skill: "schedulePosts", reason: "Internal shared draft write authority used by both the human action and Otto schedule skill." },
  "schedule-actions.createScheduledPost": { skill: "schedulePosts" },
  "schedule-actions.approveScheduledPost": { skill: "approveScheduledPost", reason: "debt-70 (B4 §五 5.1): gated skill (free/write/external → needsApproval machine-derived) + universal approval card chain + tests — the three-in-one clearance condition; the skill resumes into this SAME server action." },
  "schedule-actions.cancelScheduledPost": { skill: "cancelScheduledPost", reason: "debt-71 (B4 §五 5.2): skill goes through this same owner-scoped action via ctx.schedule.cancel." },
  "schedule-actions.updateScheduledPost": { skill: "editScheduledPost", reason: "debt-72 (B4 §五 5.2): skill goes through this same action via ctx.schedule.update — the material-edit→DRAFT/clear-approvedAt re-consent invariant lives here, inherited not re-implemented." },
  "schedule-actions.listScheduledPosts": { skill: "listScheduledPosts", reason: "debt-73 (B4 §五 5.2, read parity): skill reads through ctx.schedule.list → this same owner-scoped action." },
  "schedule-actions.listOwnerTargets": { skill: "listPublishTargets", reason: "debt-74 (B4 §五 5.2, read parity): skill reads through ctx.schedule.listTargets → this same owner-scoped action." },
  "schedule-actions.suggestPostTimes": { skill: "suggestPostTimes", reason: "B0-103 (B4 §2.2, read parity): skill reads the static posting-time seed through ctx.schedule.suggestTimes → this same action." },
  "schedule-actions.sharePostPreview": { skill: "sharePostPreview", reason: "B0-28 (B4 §2.2): skill mints a read-only share link through ctx.schedule.sharePreview → this same owner-scoped action (internal write, ungated; one SharePreviewToken authority row per mint)." },
  "schedule-actions.revokeSharePreview": { skill: "sharePostPreview", reason: "B0-28 (NODE-275 收口2): the SAME skill's revoke:true mode goes through ctx.schedule.sharePreviewRevoke → this owner-scoped action (kills every active share link for a post)." },
  "storyboard-actions.editShotPrompt": { skill: "editStoryboard" },
  "storyboard-actions.addShot": { skill: "proposeStoryboard" },
  "storyboard-actions.deleteShot": { skill: "editStoryboard" },
  "storyboard-actions.reorderShots": { skill: "editStoryboard" },
  "storyboard-gate1-actions.getStoryboardVideoOptions": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.prepareStoryboardFirstFrames": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.regenShotFirstFrameCard": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.syncStoryboardMedia": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.prepareStoryboardVideos": { skill: "proposeStoryboard" },
  "storyboard-gate1-actions.regenShotVideoCard": { skill: "proposeStoryboard" },

  "tenant-actions.setMembershipStatus": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.cutTenantSessions": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.inviteTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.revokeTenantInvite": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.impersonateTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.stopImpersonatingTenant": { exempt: "ADMIN", reason: "City Hall tenant administration is a permanent blueprint exemption." },
  "tenant-actions.grantTenantCredits": { exempt: "MONEY_IN", reason: "Admin credit grants mint money-in credits and Otto must not perform them." },
  "upload-actions.authorizeUpload": { skill: "importMedia", reason: "W-B3-B (E1-17): browser direct-upload transport for the media-import capability importMedia delivers server-side (SSRF-guarded fetch -> storage -> finalizeCandidateUploads)." },
  "upload-actions.uploadFileFallback": { skill: "importMedia", reason: "W-B3-B (E1-17): dev-driver upload fallback for the SAME media-import capability importMedia delivers server-side." },
  "upload-actions.signUploadPart": { skill: "importMedia", reason: "W-B3-B (E1-17): browser multipart transport for the media-import capability importMedia delivers server-side (single-shot <=64 MiB; larger stays the browser's chunked path)." },
  "upload-actions.abortDirectUpload": { skill: "importMedia", reason: "W-B3-B (E1-17): browser multipart-abort transport for the SAME media-import capability importMedia delivers server-side." },
  "upload-actions.finalizeCandidateUploads": { skill: "importMedia", reason: "W-B3-B (E1-17): the SAME finalize authority importMedia's ctx.mediaImport port lands imports through (Asset upsert + Generation source:UPLOAD + ingest verify)." },
  "api:better-auth/[...all].GET": { exempt: "ACCOUNT_SECURITY", reason: "Better Auth routes are account-security surfaces." },
  "api:better-auth/[...all].POST": { exempt: "ACCOUNT_SECURITY", reason: "Better Auth routes are account-security surfaces." },
  "api:health.GET": { exempt: "ADMIN", reason: "Platform liveness probe for external uptime monitors (ops surface); exposes no user capability." },
  "api:meta/authorize.GET": { exempt: "ACCOUNT_SECURITY", reason: "OAuth authorization starts external account binding." },
  "api:meta/callback.GET": { exempt: "ACCOUNT_SECURITY", reason: "OAuth callback binds external accounts and must stay human-controlled." },
  "api:meta/data-deletion.POST": { exempt: "ACCOUNT_SECURITY", reason: "Meta-initiated data-deletion callback (signed_request auth); unbinds the external account — machine-called, never Otto." },
  "api:media/pub/[token].GET": { exempt: "ADMIN", reason: "L1 signed media proxy (HMAC token) Meta's servers fetch during an already-approved publish; machine-called infra/ops surface — streams owner-scoped media bytes, exposes no Otto-operable user capability (the human already approved the post that references it)." },
  "api:otto/stream.POST": { todoSkill: true, reason: "Otto stream is the agent transport; needs a manifest convention separate from individual skills." },
  "api:otto/thread-activity.GET": { todoSkill: true, reason: "Thread activity read needs free/read skill parity." },
  "api:stripe/webhook.POST": { exempt: "MONEY_IN", reason: "Stripe webhook is money-in and authenticated by Stripe signature, not Otto." },
} as const satisfies Record<string, ParityManifestEntry>;
